Added, improved interactive objects
lrathoni/Lullaby-for-a-fish pull request #16
Opened 2021-01-16 01:45 UTC by piptouque

### What

#### Improvements 

* The *FlutePlayer* behaviour now uses Unity's State Machine implementation. It is not as now animated.

* Reworked interactive object components. They are now more fragmented and stackable. For instance, you can add a glow interaction on top of a hover.
* Reworked pause menu trigger, now invokes an event.

#### Fixes

* The hover interaction now actually makes the object hover and not just go to infinity and beyond.
* The flute is now muted upon entering the pause menu.

#### New features

* Added proper conditions for triggering OnNote events with *InteractiveRangeModifiers*, depending on the view of the camera and the distance to the object.
* Added a *PlayerAttracted* interaction which causes an object to be attracted to a position relative to the player.

#### Known issues

* Flute playing is now cluckier, you can only press a single note at all times. This is done so the flute can be properly animated.

### How to test

1. Check out this branch.
2. Open the prototype Hub scene in Unity 2019.3.
3. Enter Play mode.
4. Play the flute as usual.
5. Enter pause menu while playing and notice that the flute is muted.
6. Leave pause menu.
7. Play around with the objects. By this point anything that behaves strangely can be considered a bug, let me know if that's the case.

### Screenshots

* What I get while playing the flute. The Flute animator view should be active if the *UserInterface* game object is selected in the inspector.

![screenshot](https://user-images.githubusercontent.com/44610878/104793858-7985d880-57a4-11eb-95a9-dda38b73706b.png)

2021-01-16 19:44 UTC, roxyvallee requested changes
When I press the key " I " many times, the object keep moving up to the sky without stopping.

2021-01-16 20:18 UTC, piptouque commented
> When I press the key " I " many times, the object keep moving up to the sky without stopping.

Thanks! This is fixed with the latest commit.

2021-01-18 09:34 UTC, lrathoni approved these changes

2021-01-18 13:42 UTC, Lchikar approved these changes

2021-01-18 21:57 UTC, roxyvallee approved these changes

2021-01-19 10:34 UTC, merged